prompt("Qual é o nome da parte da bicicleta onde você senta?")
prompt("Como são chamadas as rodas da bicicleta?")
prompt("Qual é o componente que você gira para mudar as marchas da bicicleta?")
prompt("Qual é o nome da parte da bicicleta onde você segura enquanto pedala?")
prompt("O que significa 'MTB' em termos de bicicletas?")
prompt("O que significa 'BMX' em termos de bicicletas?")
prompt("Como é chamada a parte da bicicleta onde você coloca os pés enquanto pedala?")
prompt("Qual é o nome da peça que conecta o guidão à roda dianteira da bicicleta?")
prompt("Qual é a parte da bicicleta que mantém a corrente no lugar?")
prompt("O que é um 'freio a disco' em uma bicicleta?")
